name: theoffer
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.8

environment:
  sdk: ">=2.3.0 "

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_version: ^0.1.0
  cached_network_image: ^2.2.0+1
  http: ^0.12.0+4
  carousel_slider: ^1.3.0
  flutter_rating_bar: 1.3.0+1
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.2+1
  url_launcher: ^5.1.0
  connectivity: ^0.4.4
  flushbar: 1.10.2 
  get_it: ^1.0.3+2
  back_button_interceptor: ^4.1.1
  cupertino_icons: ^0.1.2
  intl: ^0.16.1
  flutter_secure_storage: 3.2.1+1
  flutter_widget_from_html_core: ^0.2.0
  flutter_launcher_icons: ^0.7.2
  flutter_pagewise: ^1.2.3
  onesignal_flutter: ^2.6.1
  datetime_picker_formfield: ^1.0.0
  mask_text_input_formatter: ^1.1.0  
  pull_to_refresh: ^1.6.3
  flutter_webview_plugin: 
    git:
      url: https://github.com/sakina1403/flutter_webview_plugin.git
  firebase_core: ^0.5.0
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  crypto: ^2.0.6  

flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "images/icon/appIcon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/
  - images/logos/
  - images/placeholders/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HolyFat
      fonts:
        - asset: fonts/Holyfat.ttf
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
        - asset: fonts/RobotoCondensed-Light.ttf
        - asset: fonts/RobotoCondensed-Bold.ttf
    - family: nutellaBold
      fonts:
        - asset: fonts/nutellaBold.ttf
        - asset: fonts/nutellaBold.ttf
        - asset: fonts/nutellaBold.ttf
